var members = [
  {
    name: "AlternativeWinter",
    github: "https://github.com/alt-win",
    avatar: "https://i.ibb.co/S0BZdk7/image.png",
    website: "",
    description: "",
    projects: "spicebutton.com",
  },
  {
    name: "Chris Troutner",
    github: "https://github.com/christroutner",
    avatar: "https://avatars0.githubusercontent.com/u/9870991?s=460&u=b0c1a02801c1b5efec87cfa74e809de265656e1b&v=4",
    website: "",
    description: "",
    projects: "fullstack.cash",
  },
  {
    name: "Dreamtrove",
    github: "https://github.com/dreamtrove",
    avatar: "https://i.ibb.co/bPKMcvt/image.png",
    website: "",
    description: "",
    projects: "",
  },
  {
    name: "JettScythe",
    github: "https://github.com/JettScythe",
    avatar: "https://avatars0.githubusercontent.com/u/37233887?s=460&u=bfa13f720e6ac1a90bcd2cd5f65704cc068a61b3&v=4",
    website: "",
    description: "",
    projects: "",
  },
  {
    name: "Kieran Mesqita",
    github: "https://github.com/mesquka",
    avatar: "https://avatars0.githubusercontent.com/u/3370615?s=460&u=260fcda1911b6a00b1fe2976afa628d2cb8df1bf&v=4",
    website: "",
    description: "",
    projects: "",
  },
  {
    name: "Sterling Beason",
    github: "https://github.com/sterlingbeason",
    avatar: "https://avatars2.githubusercontent.com/u/31223937?s=460&u=ae2bd4c909470dbe0ba0ff17c772dc7e307c7e31&v=4",
    website: "",
    description: "",
    projects: "",
  },
  {
    name: "Tigran",
    github: "https://github.com/hyetigran",
    avatar: "https://avatars2.githubusercontent.com/u/5153613?s=460&v=4",
    website: "",
    description: "",
    projects: "",
  },
  {
    name: "KBF",
    github: "github.com/KeepBitcoinFree-org",
    avatar: "https://i.ibb.co/tMLm7WZ/image.png",
    website: "https://KeepBitcoinFree.org",
    description: "",
    projects: "",
  },
  /*{
    name: "",
    github: "",
    avatar: "",
    website: "",
    description: "",
    projects: "",
  },*/
  {
    name: "Add your profile",
    github: "https://github.com/alt-win/webdevelopers.cash/blob/master/members.js",
    avatar: "https://image.flaticon.com/icons/svg/32/32339.svg",
    website: "",
    description: "",
    projects: "",
  },
];
